### ISSUE TITLE
assertion error

### ISSUE THREAD

**Issue by Fly-dream12** [flyingshan/Learning-Polar-Encodings-For-Arbitrary-Oriented-Ship-Detection-In-SAR-Images#3]
Thanks for you code, when i train the model, this error appears:
in decoder.py in polar_decode assert num_targets >0 
This happens in the evaluation process, can you give some suggestions?

**Comment by flyingshan** [comment]
I think it is caused by the <polar_decode> function in <polar.py>. When there is no target predicted, the function will fail. But recently I have no time to fix this bug, if you help fix the bug, you can give a pull request here.
p.s. I think you are using your personal dataset? if you use the SSDD dataset, I think the bug will not appear.

**Comment by Fly-dream12** [comment]
I'm using the SSDD dataset. So what may be wrong? @flyingshan

**Comment by flyingshan** [comment]
Well, I updated the README page just now, added some explanations and updated the training and testing script. See if it can help you.
